### ISSUE TITLE
sigTermHandler 오류

### ISSUE THREAD

**Issue by nara1111** [gomtings/forNEXO#2]
안녕하세요, 어제자로 커밋된 forNEXO 버전을 오늘 설치하였는데요.
selfdrive/navd/main.cc:14:23 과 15:24 에서 error: Use of undeclared identifier 'sigTermHandler' 오류가 발생합니다.

감사합니다.

**Comment by gomtings** [comment]
sigTermHandler  수정 하였으니 테스트 바랍니다.

**Comment by nara1111** [comment]
@gomtings 안녕하세요, 보고드린 오류는 해결되었으나 이제 waiting for controls to start 메시지와 함께 인식이 안됩니다.

기본적으로 @neokii 님 브랜치는 넥쏘 지원이 안되던데, 차이가 있을까요?

**Comment by gomtings** [comment]
NEXO 는 다른 차량들과 기어 쪽 캔주소가 다릅니다..
그리고 롱컨을 지원 합니다.  
오류는 다시 확인해 보겠습니다. 가능 하시면 엔튠 예외로그를 보여주시면 감사하겠습니다.

**Comment by gomtings** [comment]
몇가지 더 수정 하였습니다.. 불편하게 해드려 죄송합니다..

**Comment by nara1111** [comment]
안녕하세요, 코멘트를 늦게 봤네요. 최종 수정 버전으로 설치하였고, 다시 발생할 경우 롱컨 로그 첨부하겠습니다.
늦은 시간까지 도와주셔서 감사합니다.

**Comment by gomtings** [comment]
네 감사합니다^^

**Comment by nara1111** [comment]
안녕하세요, 늦어서 죄송합니다.
수정해주신 버전에서 정상작동 확인됩니다.
감사합니다.

**Comment by gomtings** [comment]
별남겨 주시면 감사하겠습니다 ㅎㅎ
