### ISSUE TITLE
visionipc/ipc.cc 문제

### ISSUE THREAD

**Issue by nara1111** [gomtings/forNEXO#3]
안녕하세요,
엊그제 업데이트 해주신 forNexo 브랜치 설치시 첨부한 사진과 같은 오류가 나타납니다.
![IMG_0947](https://github.com/gomtings/op_hyundai/assets/40167504/46646c3e-5778-47ba-a5b3-1b44737b6056)

**Comment by gomtings** [comment]
https://github.com/gomtings/op_hyundai/commits/forNEXO 

말슴해 주신 부분 업데이트 올려 두었습니다. 
혹시 더 문제 되는 부분 있으심 연락주세요!

**Comment by nara1111** [comment]
@gomtings 안녕하세요, 리플래싱을 해야해서 좀 헤매다가 답이 늦었습니다 ㅎㅎ
업데이트 후 정상 구동은 되는데요, 문제는 다시 차량인식을 못합니다. (Openpilot unavailable - waiting for controls to start)

아이오닉5로 기변하신거 같은데, 아무래도 제가 넥쏘 적용법을 배워야할 듯 합니다 ㅠㅠ

**Comment by gomtings** [comment]
-----Original Message-----

**Comment by gomtings** [comment]
-----Original Message-----

**Comment by nara1111** [comment]
안녕하세요, 혹시나 해서 지금 재설치 중이었습니다.
다시 해보고 말씀드리겠습니다.
바쁜시간에 도와주셔서 감사합니다!

**Comment by nara1111** [comment]
@gomtings 아... 저는 재설치해도 마찬가지네요. 로그 떠서 보내드리겠습니다.

**Comment by nara1111** [comment]
아... ntune으로 예외로그 보면 되는걸까요? 일단 예외로그는 아무 것도 뜨지 않고요.
혹시 다른 것을 봐야하나 싶어서 눌러보면 판다에 한 번도 연결된 적이 없다고 뜨네요.
흠... 혹시 agnos 리플래싱이 잘못된걸까요

**Comment by gomtings** [comment]
-----Original Message-----

**Comment by nara1111** [comment]
@gomtings 감사합니다. 혹시나 해서 우선 apilot으로 엎어봤고 정상적으로 구동되는 것으로 확인하였습니다.
(가끔 보니 reflashing 하거나 할 경우에는 판다 쪽이 제대로 엎어지지 않아서 다른 브랜치를 깔았다가 다시 설치하면 되는 경우가 있는거 같아서요. 이렇게 하고 다시 한 번 곰팅님 브랜치로 엎어보겠습니다. ㅎㅎ 도와주셔서 정말 감사합니다.)

**Comment by gomtings** [comment]
-----Original Message-----

**Comment by nara1111** [comment]
안녕하세요, 재설치 및 판다플래싱시에도 변화가 없습니다.

아래는 tmux a 로그입니다. 같은 구문이 반복되는데 controlsd만 빨간색이었습니다.

broadcast 192.168.43.255
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller
camerad clocksd proclogd micd timezoned dmonitoringmodeld encoderd loggerd modeld mapsd navmodeld sensord ui soundd locationd calibr
ationd torqued controlsd deleter dmonitoringd laikad navd pandad paramsd ubloxd pigeond plannerd radard thermald navi_controller

![Uploading IMG_0973.jpeg…]()

**Comment by nara1111** [comment]
혹시나 해서 3263f9d 버전으로 설치해봤는데 이건 또 되는군요. 로그 보니 달라진건 ipc랑 차량 목록이 생겼다는 정도인데요…

**Comment by gomtings** [comment]
과거 버전으로 할 경우 당연 동작 가능 합니다.. 확인해 보고 수정해 드리겠습니다.. 
일때문에 살펴볼 시간이 없네요..  죄송합니다..

**Comment by nara1111** [comment]
아닙니다 ㅎㅎ 일단 되면 됐죠. 도와주셔서 감사할 따름입니다.

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: sangwoo ***@***.***>
보낸 날짜: Saturday, July 1, 2023 10:32:13 AM
받는 사람: gomtings/op_hyundai ***@***.***>
참조: nara1111 ***@***.***>; Author ***@***.***>
제목: Re: [gomtings/op_hyundai] visionipc/ipc.cc 문제 (Issue #3)


과거 버전으로 할 경우 당연 동작 가능 합니다.. 확인해 보고 수정해 드리겠습니다..
일때문에 살펴볼 시간이 없네요.. 죄송합니다..

**Comment by nara1111** [comment]
OBD 쓰고 있어서 혹시나 하는 마음에 20시간 전 업데이트를 적용해 보았습니다만... ㅎㅎ
![photo_2023-07-03_22-14-11](https://github.com/gomtings/op_hyundai/assets/40167504/80863572-1aa4-454a-964e-7117441f81e1)
![photo_2023-07-03_22-14-05](https://github.com/gomtings/op_hyundai/assets/40167504/d548fc9c-5d2b-4b68-b639-826e57225861)

**Comment by gomtings** [comment]
위에 뜬 오류들 해결 했으니. 적용해 보세요... 
몇개를 빼먹고 적용했네요..

**Comment by nara1111** [comment]
흠... 안되는군요. 여전히 waiting to controls to start가 뜹니다.
빌드 자체에는 문제가 없는데 차량이 인식이 안되는 듯 하네요.
OPTK로 핑거프린트 2 떠보고 입력해주신 것과 비교해보겠습니다.

**Comment by gomtings** [comment]
새로 커밋 올렷습니다 다시 해보세요..

**Comment by nara1111** [comment]
안녕하세요. 예외로그 자체가 뜨질 않더라구요. (예외로그 접속시 빈칸)
그런데 혹시… obd를 이용한 hud가 문제일 수도 있나요?

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: sangwoo ***@***.***>
보낸 날짜: Wednesday, July 5, 2023 11:43:31 PM
받는 사람: gomtings/op_hyundai ***@***.***>
참조: nara1111 ***@***.***>; Author ***@***.***>
제목: Re: [gomtings/op_hyundai] visionipc/ipc.cc 문제 (Issue #3)


다른 분들은 문제가 없는데... 엔튠 에서 예외로그를 보내주시겠어요..? 위에 보내주신 거엔 오류가 안나와 있어서..

**Comment by nara1111** [comment]
안녕하세요, 새로 커밋하신 버전으로 설치했으나 결과가 같습니다.

코드 오류는 아닌 것 같은게 예외로그가 나오질 않습니다.


https://github.com/gomtings/op_hyundai/assets/40167504/a36c8364-47f8-47e2-bdc8-caae1c9ce24b

**Comment by gomtings** [comment]
저녁쯤에 답변 드리겠습니다.

**Comment by gomtings** [comment]
커밋 올렷습니다.

**Comment by nara1111** [comment]
안녕하세요,
최근 커밋으로 정상작동 확인하여, 장거리 운행으로 테스트해보았으나 오류가 발생하지 않았습니다.
고생 많으셨습니다. 정말 감사드립니다.
