### ISSUE TITLE
frozen importlib._bootstrap

### ISSUE THREAD

**Issue by nara1111** [gomtings/forNEXO#4]
안녕하세요, 다시 접니다.

forNEXO 브랜치에서 정상부팅 이후 다음의 메시지가 떠서 보고 드립니다.

![IMG_1066](https://github.com/gomtings/op_hyundai/assets/40167504/394671f4-1003-4c61-bc74-3a15f52c4b5a)

**Comment by gomtings** [comment]
깃풀 햇으니 다시 테스트 부탁드립니다..  경로를 잘못 적어 놨었네요..

**Comment by nara1111** [comment]
감사합니다 이틀간 테스트시 정상 작동하는 것으로 확인하였습니다.
번번히 감사드립니다.
